### ISSUE TITLE
Wrong path generation logic

### ISSUE THREAD

**Issue by max-frai** [GuillaumeGomez/html-diff-rs#13]
It seems that there is also bug in path generation. For example when you have such html:

```
<div>
   <img src="..."  />
   <div>
     <p>here will be changed content</p>
   </div>
</div>
```

Your code would generate path like `/div[1]/div[2]/p[1]` when text node (p) has been changed. But it's wrong, the number in braces is index of child of declared type. `div[2]` tell us to get 2nd div child, but there is only one and the correct path is `/div[1]/div[1]/p[1]`.

**Comment by GuillaumeGomez** [comment]
Stupid question but is it normal that your `img` tag isn't closed?

**Comment by max-frai** [comment]
Sorry, that was a typo, I've fixed it.

**Comment by max-frai** [comment]
Thank you for such response time :)
Yet another moment, indexes in XPath are not zero-based and start from one. So when you have only one html element the correct path is /html[1], when there are two divs you can access them like this: `/someparent[1]/div[1]` and `/someparent[1]/div[2]`.
So just a simple fix:
`let pos = pos.entry((*elem.name.local).to_owned()).or_insert(1);`
Insted of `or_insert(0)`. In another issue soon I will show you html example which panics.

Thanks again :)

**Comment by GuillaumeGomez** [comment]
It's a bit counter-intuitive. Maybe instead we should provide an option to allow users to pick between XPath paths and "code-like" paths?

**Comment by max-frai** [comment]
Oh, I see. Maybe the solution is to make Path struct which holds data and have two methods: to_xpath to_rawpath or something like that. And by default it should acts like `to_rawpath`.
I thought you are using xpath in rustdoc. Are you sure now, that your fix didn't broke some path logic which used your library before?

**Comment by GuillaumeGomez** [comment]
> Oh, I see. Maybe the solution is to make Path struct which holds data and have two methods: to_xpath to_rawpath or something like that. And by default it should acts like `to_rawpath`.

I didn't think about it yet. But yes, we could either do it when the user requires the content or when we generate the content directly. Maybe the first solution is better (like that you don't have to generate twice to have both kind of paths)?

> I thought you are using xpath in rustdoc. Are you sure now, that your fix didn't broke some path logic which used your library before?

No we're not. I wrote this crate and added it to rustdoc in order to make the migration from hoedown (the actual markdown renderer) to pulldown (the new one fully written in rust) easier by telling users the differences when we render their doc (no one seems to care actually so it was a huge loss of time but whatever haha).
